workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Flutter pub get
        script: |
          cd html2pdf_flutter
          flutter pub get
      - name: Build APK
        script: |
          cd html2pdf_flutter
          flutter build apk --release
    artifacts:
      - html2pdf_flutter/build/app/outputs/flutter-apk/app-release.apk
