workflows:
  android-workflow:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Flutter pub get
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
